const DEEP_CYAN = "#41b883";
const BLUE_GRAY = "#35495e";
const ARCO_DEEP_BLUE = "#1f5bfb";
const ARCO_DEEP_ORANGE = "#fe9c3e";
const ARCO_DEEP_RED = "#f66965";
const ARCO_DEEP_GREEN = "#27c24a";
const ARCO_LIGHT_BLUE = "#96bdfd";
const ARCO_LIGHT_ORANGE = "#fff7e8";
const ARCO_LIGHT_RED = "#ffece9";
const ARCO_LIGHT_GREEN = "#e8ffeb";
const MATERIAL_BLUE = "#2196f3";
const MATERIAL_GREY = "#9e9e9e";
const MATERIAL_RED = "#f44336";
const MATERIAL_YELLOW = "#ffeb3b";
const MATERIAL_GREEN = "#4caf50";
const MATERIAL_ORANGE = "#ff9800";
const MATERIAL_PURPLE = "#9c27b0";
const MATERIAL_TEAL = "#009688";
const MATERIAL_PINK = "#e91e63";
const MATERIAL_BROWN = "#795548";
const MATERIAL_CYAN = "#00bcd4";
const MATERIAL_LIME = "#cddc39";
const MATERIAL_DEEP_ORANGE = "#ff5722";
const MATERIAL_LIGHT_BLUE = "#03a9f4";
const MATERIAL_AMBER = "#ffc107";
const MATERIAL_INDIGO = "#3f51b5";
const MATERIAL_LIGHT_GREEN = "#8bc34a";
const MATERIAL_DEEP_PURPLE = "#673ab7";
const MATERIAL_YELLOW_GREEN = "#9ccc65";
const MATERIAL_DEEP_CYAN = "#006064";
const MATERIAL_DEEP_GREEN = "#2e7d32";
const MATERIAL_LIGHT_YELLOW = "#fff59d";
const MATERIAL_LIGHT_RED = "#e57373";
const MATERIAL_LIGHT_GREEN_2 = "#81c784";
const MATERIAL_LIGHT_ORANGE = "#ffcc80";
const MATERIAL_LIGHT_PURPLE = "#ba68c8";
const MATERIAL_LIGHT_GREY = "#bdbdbd";
const MATERIAL_LIGHT_PINK = "#f48fb1";
const MATERIAL_LIGHT_TEAL = "#4db6ac";
const MATERIAL_DARK_BLUE = "#0d47a1";
const MATERIAL_DARK_GREEN = "#1b5e20";
const MATERIAL_DARK_PINK = "#880e4f";
const MATERIAL_DARK_CYAN = "#00838f";
const MATERIAL_DARK_YELLOW = "#f9a825";
const MATERIAL_DARK_RED = "#b71c1c";
const MATERIAL_DARK_ORANGE = "#e65100";
const MATERIAL_DARK_GREY = "#616161";
const MATERIAL_DARK_PURPLE = "#4a148c";
const MATERIAL_DARK_TEAL = "#004d40";
const MATERIAL_DARK_LIME = "#827717";
const MATERIAL_DARK_AMBER = "#ff6f00";
const MATERIAL_DARK_INDIGO = "#1a237e";
const MATERIAL_DARK_BROWN = "#3e2723";
const MATERIAL_DARK_YELLOW_GREEN = "#689f38";
const MATERIAL_DARK_LIGHT_BLUE = "#01579b";
const MATERIAL_DARK_LIGHT_GREEN = "#33691e";
const MATERIAL_DARK_LIGHT_PINK = "#ad1457";
const MATERIAL_DARK_LIGHT_PURPLE = "#6a1b9a";
const BIG_CRY = "😭";
const ZI_BI = "🤐";
const SEE_SEXY_GIRL = "😍";
const YE_TU_LE = "🤮";
const XIAO_NI_MA = "😅";
const MANY_BUGS = "😱";
const FO_ZU_BAO_YOU = "😇";
const MEI_LIAN_JIAN_REN = "🙈";
const XIAO_CHOU = "🤡";
const SHUT_UP = "🤫";
const GUI = "👻";
const YI_TUO_SHI = "💩";
const MEI_NAO_ZI = "🧠";
const DAO_LE_CHAN_PIN = "🔪";
const SONG_NI_SHANG_XI_TIAN = "🚀";
const CHI_YAO_LE_DA_LANG = "💊";
const SHANG_XIAN_LE = "🎉";
const BLACK_FACE = "🌚";
const YE_ZI_SHU = "🌴";
const SONG_SHU = "🌲";
const XIAN_REN_ZHANG = "🌵";
const JU_GE_LI_ZI = "🌰";
const DIAN_ZAN = "👍";
const ZERO_BUG = "🙏";
const OK = "👌";
const CALL_ME_TONIGHT = "🤙";
const FINGER_RIGHT = "👉";
const FINGER_LEFT = "👈";
const FINGER_UP = "👆";
const FINGER_DOWN = "👇";
const HE_ZUO_YU_KUAI = "🤝";
const PEI_ZHONG_DA_FEI_ZHU = "🐷";
const NEW_BEE = "🐝";
const WANG_WANG_DUI = "🐶";
const NIU = "🐮";
const KUN = "🐔";
const WATERMELON = "🍉";
const GREEN_TEA = "🍵";
const APPLE = "🍎";
const HAMBURGER = "🍔";
const CHEERS = "🍻";
export {
  APPLE,
  ARCO_DEEP_BLUE,
  ARCO_DEEP_GREEN,
  ARCO_DEEP_ORANGE,
  ARCO_DEEP_RED,
  ARCO_LIGHT_BLUE,
  ARCO_LIGHT_GREEN,
  ARCO_LIGHT_ORANGE,
  ARCO_LIGHT_RED,
  BIG_CRY,
  BLACK_FACE,
  BLUE_GRAY,
  CALL_ME_TONIGHT,
  CHEERS,
  CHI_YAO_LE_DA_LANG,
  DAO_LE_CHAN_PIN,
  DEEP_CYAN,
  DIAN_ZAN,
  FINGER_DOWN,
  FINGER_LEFT,
  FINGER_RIGHT,
  FINGER_UP,
  FO_ZU_BAO_YOU,
  GREEN_TEA,
  GUI,
  HAMBURGER,
  HE_ZUO_YU_KUAI,
  JU_GE_LI_ZI,
  KUN,
  MANY_BUGS,
  MATERIAL_AMBER,
  MATERIAL_BLUE,
  MATERIAL_BROWN,
  MATERIAL_CYAN,
  MATERIAL_DARK_AMBER,
  MATERIAL_DARK_BLUE,
  MATERIAL_DARK_BROWN,
  MATERIAL_DARK_CYAN,
  MATERIAL_DARK_GREEN,
  MATERIAL_DARK_GREY,
  MATERIAL_DARK_INDIGO,
  MATERIAL_DARK_LIGHT_BLUE,
  MATERIAL_DARK_LIGHT_GREEN,
  MATERIAL_DARK_LIGHT_PINK,
  MATERIAL_DARK_LIGHT_PURPLE,
  MATERIAL_DARK_LIME,
  MATERIAL_DARK_ORANGE,
  MATERIAL_DARK_PINK,
  MATERIAL_DARK_PURPLE,
  MATERIAL_DARK_RED,
  MATERIAL_DARK_TEAL,
  MATERIAL_DARK_YELLOW,
  MATERIAL_DARK_YELLOW_GREEN,
  MATERIAL_DEEP_CYAN,
  MATERIAL_DEEP_GREEN,
  MATERIAL_DEEP_ORANGE,
  MATERIAL_DEEP_PURPLE,
  MATERIAL_GREEN,
  MATERIAL_GREY,
  MATERIAL_INDIGO,
  MATERIAL_LIGHT_BLUE,
  MATERIAL_LIGHT_GREEN,
  MATERIAL_LIGHT_GREEN_2,
  MATERIAL_LIGHT_GREY,
  MATERIAL_LIGHT_ORANGE,
  MATERIAL_LIGHT_PINK,
  MATERIAL_LIGHT_PURPLE,
  MATERIAL_LIGHT_RED,
  MATERIAL_LIGHT_TEAL,
  MATERIAL_LIGHT_YELLOW,
  MATERIAL_LIME,
  MATERIAL_ORANGE,
  MATERIAL_PINK,
  MATERIAL_PURPLE,
  MATERIAL_RED,
  MATERIAL_TEAL,
  MATERIAL_YELLOW,
  MATERIAL_YELLOW_GREEN,
  MEI_LIAN_JIAN_REN,
  MEI_NAO_ZI,
  NEW_BEE,
  NIU,
  OK,
  PEI_ZHONG_DA_FEI_ZHU,
  SEE_SEXY_GIRL,
  SHANG_XIAN_LE,
  SHUT_UP,
  SONG_NI_SHANG_XI_TIAN,
  SONG_SHU,
  WANG_WANG_DUI,
  WATERMELON,
  XIAN_REN_ZHANG,
  XIAO_CHOU,
  XIAO_NI_MA,
  YE_TU_LE,
  YE_ZI_SHU,
  YI_TUO_SHI,
  ZERO_BUG,
  ZI_BI
};
